# CheckHub 系统设置示例
# 复制此文件为 settings.toml 并修改配置

# ========================================
# 管理员账户配置
# ========================================
[admin]
username = "admin"
password = "admin123"  # ⚠️ 首次登录后请立即修改密码！

# ========================================
# Telegram 通知配置
# ========================================
[notifications.telegram]
enabled = false  # 改为 true 启用 Telegram 通知
bot_token = "YOUR_BOT_TOKEN"  # 替换为你的 Bot Token
chat_id = "YOUR_CHAT_ID"      # 替换为你的 Chat ID

# 获取方式：
# 1. 在 Telegram 中搜索 @BotFather
# 2. 发送 /newbot 创建新 Bot，获取 Token
# 3. 在 Telegram 中搜索 @userinfobot，获取 Chat ID

# ========================================
# 钉钉通知配置
# ========================================
[notifications.dingtalk]
enabled = false  # 改为 true 启用钉钉通知
webhook = "YOUR_WEBHOOK_URL"  # 替换为钉钉机器人 Webhook URL
secret = "YOUR_SECRET"        # 替换为加签密钥（如果启用了加签）

# 获取方式：
# 1. 打开钉钉群聊
# 2. 群设置 -> 智能群助手 -> 添加机器人
# 3. 选择"自定义"机器人
# 4. 设置安全设置（推荐使用加签）
# 5. 复制 Webhook URL 和密钥

# ========================================
# 定时任务配置
# ========================================
[scheduler]
enabled = true  # 是否启用定时任务（仅 Web 模式有效）
check_time = "08:00"  # 签到时间，24小时制（如 "08:00"、"20:30"）

# 注意：
# - 定时任务仅在 Web 模式（python run.py）下有效
# - 命令行模式（python checkin.py）需要配合 Cron 或 Systemd Timer 使用
# - 时间格式：HH:MM（如 08:00 表示早上 8 点，20:30 表示晚上 8 点 30 分）

# ========================================
# 配置说明
# ========================================
# 1. 所有密码和密钥都是敏感信息，请妥善保管
# 2. 不要将此配置文件提交到公开的 Git 仓库
# 3. 建议定期备份配置文件
# 4. 修改配置后需要重启服务才能生效
